name = "cek_kuota_vpn"
main = "worker.js"
compatibility_date = "2024-01-01"

account_id = "2be8757c27accc0e32b2e7b191dab316"

# KV kalau nanti mau dipakai
kv_namespaces = [
  { binding = "USER_VPN", id = "dff1b5e600a14e6c8b51b6f1ca2434ee" },
  { binding = "PROFILE_PIC", id = "bd884cff26074fa4988d5be44108d7fc" }
]
# Static assets (index.html, js, css, dll)
[assets]
directory = "./public"

# VARS BIASA (bukan secret Cloudflare)
[vars]
AUTH_BASIC = "c2lkb21wdWxhcGk6YXBpZ3drbXNw"
X_API_KEY = "60ef29aa-a648-4668-90ae-20951ef90c55"
X_APP_VERSION = "4.0.0"
