name = "cek_kuota_vpn"
main = "worker.js"
compatibility_date = "2024-01-01"

account_id = "7431e1cb1076e540960f6796b8971a49"

# KV kalau nanti mau dipakai
kv_namespaces = [
  { binding = "USER_VPN", id = "16a8f179b2ee4743a0dd49892bbee3ee" }
]

# Static assets (index.html, js, css, dll)
[assets]
directory = "./public"

# VARS BIASA (bukan secret Cloudflare)
[vars]
AUTH_BASIC = "c2lkb21wdWxhcGk6YXBpZ3drbXNw"
X_API_KEY = "60ef29aa-a648-4668-90ae-20951ef90c55"
X_APP_VERSION = "4.0.0"
